apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-61p-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit323-61p-app
  template:
    metadata:
      labels:
        app: sit323-61p-app
    spec:
      containers:
      - name: sit323-61p-app
        image: oguricapp/sit323-61p-app
        ports:
        - containerPort: 8080
